#!/bin/bash

if [ -z "`which docker`" ]; then
  echo "Docker not installed"
  exit 1
fi

if [ -z "`which docker-compose`" ]; then
  echo "Docker Compose not installed"
  exit 1
fi

ACTION=${ACTION:-deploy}

SERVER_PROTOCOL=http
SERVER_PORT=${PORT:-8080}
SERVER_IP=${IP}

if [ "$ACTION" = "deploy" ]; then
  set -e

  echo "Pulling production docker-compose.yml"
  echo "================================================="
  wget https://raw.githubusercontent.com/dakotalightning/docker-rails/master/docker-production.yml -O docker-compose.yml

  echo " -> Pulling images"
  echo "================================================="
  docker pull dakotalightning/docker-nginx
  docker pull dakotalightning/docker-rails

  echo " -> Starting containers"
  docker-compose up -d
  docker-compose ps
  docker ps

else
  echo "${red} Unknown action $ACTION${reset}"
  exit 1
fi
