#!/bin/bash

# ssh user@host 'bash -s' < /path/script.sh

if [ -z "`which docker`" ]; then
  echo "Docker not installed"
  exit 1
fi

if [ -z "`which docker-compose`" ]; then
  echo "Docker Compose not installed"
  exit 1
fi

ACTION=${ACTION:-deploy}

if [ "$ACTION" = "deploy" ]; then
  set -e

  echo " --> Pulling new images"
  echo "=================================================================="
  docker pull dakotalightning/docker-nginx
  docker pull dakotalightning/docker-rails

  echo " --> Pulling production conpose config"
  echo "=================================================================="
  # wget https://raw.githubusercontent.com/dakotalightning/docker-rails/master/docker-production.yml -O docker-compose.yml

  echo " --> Starting up containers"
  echo "=================================================================="
  docker-compose up -d
  docker-compose ps
  docker ps
  echo " --> Done"

else
  echo "${red} Unknown action $ACTION${reset}"
  exit 1
fi
