#!/bin/bash

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

if [ -z "`which docker`" ]; then
  echo "${red}Docker not installed${reset}"
  exit 1
fi

if [ -z "`which docker-compose`" ]; then
  echo "${red}Docker Compose not installed${reset}"
  exit 1
fi

ACTION=${ACTION:-deploy}

if [ "$ACTION" = "deploy" ]; then
  set -e

  echo "${green}Clearing containers${reset}"
  echo "${green}=================================================${reset}"
  docker-compose rm -f

  echo "${green}Update nginx${reset}"
  echo "${green} ----> Building nginx production image${reset}"
  echo "${green}=================================================${reset}"
  docker build -t dakotalightning/docker-nginx ./nginx

  echo "${green} ----> Pushing nginx${reset}"
  echo "${green}=================================================${reset}"
  docker push dakotalightning/docker-nginx

  echo "${green}Update web${reset}"
  echo "${green} ----> Building web production image${reset}"
  echo "${green}=================================================${reset}"
  docker build -t dakotalightning/docker-rails -f ./web/Dockerfile.production ./web

  echo "${green} ----> Pushing web${reset}"
  echo "${green}=================================================${reset}"
  docker push dakotalightning/docker-rails

  echo "${green} ----> Images updated ${reset}"
  echo "${green}=================================================${reset}"
else
  echo "${red} Unknown action $ACTION${reset}"
  exit 1
fi
