#!/bin/bash

echo " -> Starting containers"
docker-compose up -d; sleep 20

echo " - Continuing with app database setup:"

echo " -> Reseting database"
echo "================================================="
docker-compose run --rm web rake db:drop && rake db:create && rake db:migrate
