#!/bin/bash

green=`tput setaf 2`
reset=`tput sgr0`

echo "${green}Clearing containers${reset}"
docker-compose rm -f

echo "${green} --> Starting containers${reset}"
docker-compose up -d; sleep 20

echo "${green}Continuing with app database setup${reset}"
echo "${green} --> Reseting database${reset}"
echo "${green}====================================================================${reset}"
docker-compose run --rm web rake db:setup

echo "${green}====================================================================${reset}"
docker-compose ps
