web:
  build: .
  volumes:
    - .:/var/myapp
  ports:
    - "3000:3000"
  links:
    - db
  # reference to https://github.com/docker/compose/issues/1393 where the pid isn't removed on cleanup
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
db:
  image: mysql
  ports:
    - "13306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
